- name: Set hostname
  hostname:
    name: perfsuite

- name: Create group {{ group }}
  group:
    name: "{{ group }}"
    state: present

- name: Create user {{ user }}
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    password: "{{ user_password }}"
    update_password: always
    shell: /bin/bash
    state: present

- name: Install psql
  apt:
    name: "{{ item }}"
  with_items:
    - postgresql-client
    - curl
  update_cache: yes
