version: '2'
services:
  qgis-2.14:
    container_name: qgisserver-perfsuite-2.14
    image: qgisserver-perfsuite/2.14
    volumes:
      - ./data:/data
    links:
      - data
  qgis-2.18:
    container_name: qgisserver-perfsuite-2.18
    image: qgisserver-perfsuite/2.18
    volumes:
      - ./data:/data
    links:
      - data
  qgis-3.0:
    container_name: qgisserver-perfsuite-3.0
    image: qgisserver-perfsuite/3.0
    volumes:
      - ./data:/data
    links:
      - data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0
  qgis-3.0-parallel-rendering:
    container_name: qgisserver-perfsuite-3.0-parallel-rendering
    image: qgisserver-perfsuite/3.0
    volumes:
      - ./data:/data
    links:
      - data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=1
      - QGIS_SERVER_MAX_THREADS=4
  qgis-master:
    container_name: qgisserver-perfsuite-master
    image: qgisserver-perfsuite/master
    volumes:
      - ./data:/data
    links:
      - data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0
  qgis-master-parallel-rendering:
    container_name: qgisserver-perfsuite-master-parallel-rendering
    image: qgisserver-perfsuite/master
    volumes:
      - ./data:/data
    links:
      - data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=1
      - QGIS_SERVER_MAX_THREADS=4
  data:
    container_name: qgisserver-perfsuite-data
    image: qgisserver-perfsuite/data
