version: '2'
services:
  nginx:
    container_name: qgisserver-perfsuite-nginx
    image: nginx:1.13
    ports:
      - 8088:80
    networks:
      - qgis
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qgis-2.18
      - qgis-3.10
      - qgis-3.14
      - qgis-master
  qgis-2.18:
    container_name: qgisserver-perfsuite-2.18
    image: qgisserver-perfsuite/2.18
    networks:
      - qgis
      - data
    volumes:
      - ../docker/data/data:/data
  qgis-3.10:
    container_name: qgisserver-perfsuite-3.10
    image: qgisserver-perfsuite/3.10
    networks:
      - qgis
      - data
    volumes:
      - ../docker/data/data:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0
  qgis-3.14:
    container_name: qgisserver-perfsuite-3.14
    image: qgisserver-perfsuite/3.14
    networks:
      - qgis
      - data
    volumes:
      - ../docker/data/data:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0
  qgis-master:
    container_name: qgisserver-perfsuite-master
    image: qgisserver-perfsuite/master
    networks:
      - qgis
      - data
    volumes:
      - ../docker/data/data:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0
  data:
    container_name: qgisserver-perfsuite-data
    image: qgisserver-perfsuite/data
    ports:
      - 55432:5432
    networks:
      - data

networks:
  data:
    driver: bridge
  qgis:
    driver: bridge
